#include "ChessLessons.h"

const ChessLesson CHESS_LESSONS[CHESS_LESSON_COUNT] =
{
	{ "Ze Centre", "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1",
	  { "e4. ze oldest move und still ze best one.",
	    "ze centre is high ground. take it first,",
	    "argue about ze rest later." },
	  "e2e4", nullptr, "nein. ze centre. claim your half of it." },
	{ "Ze Fork", "2r3k1/8/8/3N4/8/8/8/4K3 w - - 0 1",
	  { "one knight, two targets. zey cannot both leave.",
	    "ze fork is not clever. it is arithmetic.",
	    "check comes first. zen you take ze rook." },
	  "d5e7", nullptr, "no. find ze square zat touches both of zem." },
	{ "Ze Back Rank", "6k1/5ppp/8/8/8/8/5PPP/4R1K1 w - - 0 1",
	  { "ze king built a house. ze house is a coffin.",
	    "Re8 is mate. ze pawns do not help - zey block.",
	    "give your king air before zis happens to you." },
	  "e1e8", nullptr, "not zat. ze back rank stands open - use it." },
	{ "Ze Pin", "4k3/8/2n5/3P4/B7/8/8/4K3 w - - 0 1",
	  { "ze knight cannot move. it only looks like a knight.",
	    "pinned to ze king, a piece is paper.",
	    "take it. it cannot run." },
	  "d5c6", "a4c6", "ze knight is paper. treat it like paper." },
	{ "Ze Passed Pawn", "8/1p6/8/3P4/8/8/8/k1K5 w - - 0 1",
	  { "no pawn can stop it. count ze files: none.",
	    "a passed pawn is a promise. push it.",
	    "ze rest of ze board is a distraction." },
	  "d5d6", nullptr, "push. ze pawn does not walk itself." },
	{ "Ze Castle", "rnbq1rk1/pppp1ppp/5n2/2b1p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQ - 6 5",
	  { "two moves in one. ze only bargain in chess.",
	    "king to safety, rook to work.",
	    "do it early. regret is not a defence." },
	  "e1g1", nullptr, "castle. ze black king already lives in safety." },
	{ "Ze Skewer", "8/8/8/4q3/4k3/8/8/R6K w - - 0 1",
	  { "like ze pin, but ze big one stands in front.",
	    "ze king steps aside, politely. zen you take.",
	    "royalty first: zat is ze skewer." },
	  "a1e1", nullptr, "check ze king. royalty first, always." },
	{ "Ze Open File", "5rk1/ppp2ppp/8/8/8/8/PPP2PPP/3R2K1 w - - 0 1",
	  { "a file wiz no pawns is a road.",
	    "ze rook is a highway animal. give it asphalt.",
	    "first to ze open file collects ze seventh rank." },
	  "d1d7", nullptr, "ze rook belongs on ze road, all ze way up it." },
};
