#ifndef CHESSPUZZLES_H
#define CHESSPUZZLES_H

// Generated by docs/custom_artworks_source/laptop/import_chess_puzzles.py
// Do not edit by hand - re-run the importer against the puzzle database.

// One daily puzzle, in Lichess's layout.
//
// fen is the position BEFORE the setup move, and the first move in `moves` is
// the opponent's. Play that move to reach the position the player is asked to
// solve, which also means the solver is the side opposite the FEN's side to
// move. From there the solver's moves are at even indices of the remainder and
// the scripted replies at odd ones.
struct ChessPuzzle
{
	const char* id;
	const char* fen;
	const char* moves;
	const char* themes;
	const char* title;
	short       rating;
};

extern const ChessPuzzle CHESS_PUZZLES[];
extern const int NUM_CHESS_PUZZLES;

#endif
