#include "ChessLessons.h"

const ChessLesson CHESS_LESSONS[CHESS_LESSON_COUNT] =
{
	{ "Ze Centre", "rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq e3 0 1",
	  { "e4. ze oldest move und still ze best one.",
	    "ze centre is high ground. take it first,",
	    "argue about ze rest later." } },
	{ "Ze Fork", "8/2r1k3/8/3N4/8/8/8/4K3 w - - 0 1",
	  { "one knight, two targets. zey cannot both leave.",
	    "ze fork is not clever. it is arithmetic.",
	    "check comes first. zen you take ze rook." } },
	{ "Ze Back Rank", "6k1/5ppp/8/8/8/8/5PPP/4R1K1 w - - 0 1",
	  { "ze king built a house. ze house is a coffin.",
	    "Re8 is mate. ze pawns do not help - zey block.",
	    "give your king air before zis happens to you." } },
	{ "Ze Pin", "4k3/8/2n5/8/B7/8/8/4K3 w - - 0 1",
	  { "ze knight cannot move. it only looks like a knight.",
	    "pinned to ze king, a piece is paper.",
	    "attack it again. it cannot run." } },
	{ "Ze Passed Pawn", "8/1p6/8/3P4/8/8/8/k1K5 w - - 0 1",
	  { "no pawn can stop it. count ze files: none.",
	    "a passed pawn is a promise. push it.",
	    "ze rest of ze board is a distraction." } },
	{ "Ze Castle", "rnbq1rk1/pppp1ppp/5n2/2b1p3/2B1P3/5N2/PPPP1PPP/RNBQ1RK1 w - - 6 5",
	  { "two moves in one. ze only bargain in chess.",
	    "king to safety, rook to work.",
	    "do it early. regret is not a defence." } },
	{ "Ze Skewer", "8/8/8/4q3/8/4k3/8/4R2K b - - 0 1",
	  { "like ze pin, but ze big one stands in front.",
	    "ze king steps aside, politely. zen you take.",
	    "royalty first: zat is ze skewer." } },
	{ "Ze Open File", "5rk1/ppp2ppp/8/8/8/8/PPP2PPP/3R2K1 w - - 0 1",
	  { "a file wiz no pawns is a road.",
	    "ze rook is a highway animal. give it asphalt.",
	    "first to ze open file collects ze seventh rank." } },
};
